export const projects = [
    {
      projectName: 'Film Finder',
      projectGitHub: 'https://github.com/Cgotts1/API-Project',
      projectSite:'https://cgotts1.github.io/Film-Finder/',
      projectImage: 'https://cgotts1.github.io/V4-Portfolio/images/film-finder.jpg',
      projectSummary: 'A movie search web application that utilizes two APIs and local storage to render a movie\'s information and its respective movie poster.',
    },
    // {
    //   projectName: 'ChewToy',
    //   projectGitHub: '',
    //   projectSite:'',
    //   projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //   projectSummary: 'I don\'t like cats at all.',
    // },
    // {
    //   projectName: 'BuryHeadInSand',
    //   projectGitHub: '',
    //   projectSite:'',
    //   projectImage: 'https://images.unsplash.com/photo-1563482776068-4dac10f9373d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    //   projectSummary: 'Wild ostriches make the best pets.',
    // },
    // {
    //   projectName: 'ScrungeCat',
    //   projectGitHub: '',
    //   projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
    //   {
    //     projectName: 'ScrungeCat',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
    //   {
    //     projectName: 'ScrungeCat',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
    //   {
    //     projectName: 'ScrungeCat',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
    //   {
    //     projectName: 'ScrungeCat',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
    //   {
    //     projectName: 'ScrungeCat',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1609992556706-14a7056ea745?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1287&q=80',
    //     projectSummary: 'My favorite types of cats are slightly weird looking ones!',
    //   },
    //   {
    //     projectName: 'ChewToy',
    //     projectGitHub: '',
    //     projectSite:'',
    //     projectImage: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
    //     projectSummary: 'I don\'t like cats at all.',
    //   },
  ]
